# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

opt_out_usage
default_platform(:ios)

before_all do
  xcversion(version: "11.4")
end

platform :ios do
  desc "Run tests"
  lane :test do
    scan
  end
end
