name: CI

on:
  push:
    branches:
      - develop
      - feature/*

jobs:
  test:
    name: Test
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache RubyGems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Bundle Install
        run: bundle install --jobs 4 --retry 3

      - name: Build and test
        run: bundle exec fastlane scan
